exported: true
with-expecter: true
dir: mocks
outpkg: mocks

packages:
  github.com/wheelibin/hugh/internal/schedule:
    config:
      all: true
  github.com/wheelibin/hugh/internal/physicalStateManager:
    config:
      all: true
