// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/wheelibin/hugh/internal/models"
)

// MockdbAccess is an autogenerated mock type for the dbAccess type
type MockdbAccess struct {
	mock.Mock
}

type MockdbAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdbAccess) EXPECT() *MockdbAccess_Expecter {
	return &MockdbAccess_Expecter{mock: &_m.Mock}
}

// GetAllControllingLightIDs provides a mock function with given fields:
func (_m *MockdbAccess) GetAllControllingLightIDs() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdbAccess_GetAllControllingLightIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllControllingLightIDs'
type MockdbAccess_GetAllControllingLightIDs_Call struct {
	*mock.Call
}

// GetAllControllingLightIDs is a helper method to define mock.On call
func (_e *MockdbAccess_Expecter) GetAllControllingLightIDs() *MockdbAccess_GetAllControllingLightIDs_Call {
	return &MockdbAccess_GetAllControllingLightIDs_Call{Call: _e.mock.On("GetAllControllingLightIDs")}
}

func (_c *MockdbAccess_GetAllControllingLightIDs_Call) Run(run func()) *MockdbAccess_GetAllControllingLightIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockdbAccess_GetAllControllingLightIDs_Call) Return(_a0 []string, _a1 error) *MockdbAccess_GetAllControllingLightIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdbAccess_GetAllControllingLightIDs_Call) RunAndReturn(run func() ([]string, error)) *MockdbAccess_GetAllControllingLightIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSceneIDs provides a mock function with given fields:
func (_m *MockdbAccess) GetAllSceneIDs() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdbAccess_GetAllSceneIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSceneIDs'
type MockdbAccess_GetAllSceneIDs_Call struct {
	*mock.Call
}

// GetAllSceneIDs is a helper method to define mock.On call
func (_e *MockdbAccess_Expecter) GetAllSceneIDs() *MockdbAccess_GetAllSceneIDs_Call {
	return &MockdbAccess_GetAllSceneIDs_Call{Call: _e.mock.On("GetAllSceneIDs")}
}

func (_c *MockdbAccess_GetAllSceneIDs_Call) Run(run func()) *MockdbAccess_GetAllSceneIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockdbAccess_GetAllSceneIDs_Call) Return(_a0 []string, _a1 error) *MockdbAccess_GetAllSceneIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdbAccess_GetAllSceneIDs_Call) RunAndReturn(run func() ([]string, error)) *MockdbAccess_GetAllSceneIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetLightTargetState provides a mock function with given fields: lsID
func (_m *MockdbAccess) GetLightTargetState(lsID string) (models.LightState, error) {
	ret := _m.Called(lsID)

	var r0 models.LightState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.LightState, error)); ok {
		return rf(lsID)
	}
	if rf, ok := ret.Get(0).(func(string) models.LightState); ok {
		r0 = rf(lsID)
	} else {
		r0 = ret.Get(0).(models.LightState)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lsID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdbAccess_GetLightTargetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLightTargetState'
type MockdbAccess_GetLightTargetState_Call struct {
	*mock.Call
}

// GetLightTargetState is a helper method to define mock.On call
//   - lsID string
func (_e *MockdbAccess_Expecter) GetLightTargetState(lsID interface{}) *MockdbAccess_GetLightTargetState_Call {
	return &MockdbAccess_GetLightTargetState_Call{Call: _e.mock.On("GetLightTargetState", lsID)}
}

func (_c *MockdbAccess_GetLightTargetState_Call) Run(run func(lsID string)) *MockdbAccess_GetLightTargetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockdbAccess_GetLightTargetState_Call) Return(_a0 models.LightState, _a1 error) *MockdbAccess_GetLightTargetState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdbAccess_GetLightTargetState_Call) RunAndReturn(run func(string) (models.LightState, error)) *MockdbAccess_GetLightTargetState_Call {
	_c.Call.Return(run)
	return _c
}

// GetSceneTargetState provides a mock function with given fields: id
func (_m *MockdbAccess) GetSceneTargetState(id string) (models.LightState, error) {
	ret := _m.Called(id)

	var r0 models.LightState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.LightState, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.LightState); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.LightState)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdbAccess_GetSceneTargetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSceneTargetState'
type MockdbAccess_GetSceneTargetState_Call struct {
	*mock.Call
}

// GetSceneTargetState is a helper method to define mock.On call
//   - id string
func (_e *MockdbAccess_Expecter) GetSceneTargetState(id interface{}) *MockdbAccess_GetSceneTargetState_Call {
	return &MockdbAccess_GetSceneTargetState_Call{Call: _e.mock.On("GetSceneTargetState", id)}
}

func (_c *MockdbAccess_GetSceneTargetState_Call) Run(run func(id string)) *MockdbAccess_GetSceneTargetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockdbAccess_GetSceneTargetState_Call) Return(_a0 models.LightState, _a1 error) *MockdbAccess_GetSceneTargetState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdbAccess_GetSceneTargetState_Call) RunAndReturn(run func(string) (models.LightState, error)) *MockdbAccess_GetSceneTargetState_Call {
	_c.Call.Return(run)
	return _c
}

// MarkLightAsUpdated provides a mock function with given fields: lsID
func (_m *MockdbAccess) MarkLightAsUpdated(lsID string) error {
	ret := _m.Called(lsID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(lsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdbAccess_MarkLightAsUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkLightAsUpdated'
type MockdbAccess_MarkLightAsUpdated_Call struct {
	*mock.Call
}

// MarkLightAsUpdated is a helper method to define mock.On call
//   - lsID string
func (_e *MockdbAccess_Expecter) MarkLightAsUpdated(lsID interface{}) *MockdbAccess_MarkLightAsUpdated_Call {
	return &MockdbAccess_MarkLightAsUpdated_Call{Call: _e.mock.On("MarkLightAsUpdated", lsID)}
}

func (_c *MockdbAccess_MarkLightAsUpdated_Call) Run(run func(lsID string)) *MockdbAccess_MarkLightAsUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockdbAccess_MarkLightAsUpdated_Call) Return(_a0 error) *MockdbAccess_MarkLightAsUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdbAccess_MarkLightAsUpdated_Call) RunAndReturn(run func(string) error) *MockdbAccess_MarkLightAsUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// SetLightUnreachable provides a mock function with given fields: lsID
func (_m *MockdbAccess) SetLightUnreachable(lsID string) error {
	ret := _m.Called(lsID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(lsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdbAccess_SetLightUnreachable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLightUnreachable'
type MockdbAccess_SetLightUnreachable_Call struct {
	*mock.Call
}

// SetLightUnreachable is a helper method to define mock.On call
//   - lsID string
func (_e *MockdbAccess_Expecter) SetLightUnreachable(lsID interface{}) *MockdbAccess_SetLightUnreachable_Call {
	return &MockdbAccess_SetLightUnreachable_Call{Call: _e.mock.On("SetLightUnreachable", lsID)}
}

func (_c *MockdbAccess_SetLightUnreachable_Call) Run(run func(lsID string)) *MockdbAccess_SetLightUnreachable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockdbAccess_SetLightUnreachable_Call) Return(_a0 error) *MockdbAccess_SetLightUnreachable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdbAccess_SetLightUnreachable_Call) RunAndReturn(run func(string) error) *MockdbAccess_SetLightUnreachable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdbAccess creates a new instance of MockdbAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdbAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdbAccess {
	mock := &MockdbAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
