// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/wheelibin/hugh/internal/models"
)

// MocklightRepo is an autogenerated mock type for the lightRepo type
type MocklightRepo struct {
	mock.Mock
}

type MocklightRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MocklightRepo) EXPECT() *MocklightRepo_Expecter {
	return &MocklightRepo_Expecter{mock: &_m.Mock}
}

// UpdateTargetState provides a mock function with given fields: scheduleName, target
func (_m *MocklightRepo) UpdateTargetState(scheduleName string, target models.LightState) error {
	ret := _m.Called(scheduleName, target)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, models.LightState) error); ok {
		r0 = rf(scheduleName, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocklightRepo_UpdateTargetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTargetState'
type MocklightRepo_UpdateTargetState_Call struct {
	*mock.Call
}

// UpdateTargetState is a helper method to define mock.On call
//   - scheduleName string
//   - target models.LightState
func (_e *MocklightRepo_Expecter) UpdateTargetState(scheduleName interface{}, target interface{}) *MocklightRepo_UpdateTargetState_Call {
	return &MocklightRepo_UpdateTargetState_Call{Call: _e.mock.On("UpdateTargetState", scheduleName, target)}
}

func (_c *MocklightRepo_UpdateTargetState_Call) Run(run func(scheduleName string, target models.LightState)) *MocklightRepo_UpdateTargetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.LightState))
	})
	return _c
}

func (_c *MocklightRepo_UpdateTargetState_Call) Return(_a0 error) *MocklightRepo_UpdateTargetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocklightRepo_UpdateTargetState_Call) RunAndReturn(run func(string, models.LightState) error) *MocklightRepo_UpdateTargetState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocklightRepo creates a new instance of MocklightRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocklightRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocklightRepo {
	mock := &MocklightRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
